services:
  # app:
  #   container_name: avito_app
  #   build: "."
  #   ports:
  #     - "${HTTP_PORT}:${HTTP_PORT}"
  #   restart: on-failure:5
  #   tty: true
  #   stdin_open: true
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres
  #   networks:
  #     - avito_network

  postgres:
    container_name: avito_postgres
    image: postgres:15.2-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - .env
    networks:
      - avito_network

  migrate:
    container_name: avito_migrate
    image: migrate/migrate
    env_file:
      - .env
    volumes:
      - ./db/migrations:/migrations
    command: [ "-path", "/migrations", "-database", "postgres://${PGUSER}:${PGPASSWORD}@postgres/${PGDATABASE}?sslmode=${PGSSLMODE}", "up" ]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - avito_network

volumes:
  postgres_data:

networks:
  avito_network:
    name: avito_network
    driver: bridge
